package it.uniroma2.utils;

public enum DataField {
    /* Intra run data fields */
    TIMESTAMP,
    R_0,
    SCALING_INDICATOR,
    TO_BE_ACTIVE,
    ACTIVE,
    TO_BE_REMOVED,
    REMOVED,
    EVENT_TYPE_JOB,
    EVENT_TYPE_SCALING,
    COMPLETING_SERVER_INDEX,
    PER_JOB_RESPONSE_TIME,
    JOBS_IN_SERVER,
    JOBS_IN_SYSTEM,
    STATUS_OF_SERVER,
    SPIKE_CURRENT_CAPACITY,
    JOB_SIZE,
    NEXT_INTERARRIVAL_TIME,

    /* Intra run transient data fields */
    AGG_SYSTEM_RESPONSE_TIME,
    AGG_SYSTEM_JOB_NUMBER,
    AGG_SYSTEM_UTILIZATION,
    AGG_SYSTEM_ALLOCATED_CAPACITY_PER_SEC,
    AGG_SERVER_RESPONSE_TIME,
    AGG_SERVER_JOB_NUMBER,
    AGG_SERVER_UTILIZATION,
    AGG_SERVER_ALLOCATED_CAPACITY_PER_SEC,

    /* Intra run Batch means data fields */
    BM_SYSTEM_RESPONSE_TIME,
    BM_SERVER_RESPONSE_TIME,
    BM_SYSTEM_JOB_NUMBER,
    BM_SERVER_JOB_NUMBER,
    BM_SYSTEM_UTILIZATION,
    BM_SERVER_UTILIZATION,
    BM_SYSTEM_ALLOCATED_CAPACITY_PER_SEC,
    BM_SERVER_ALLOCATED_CAPACITY_PER_SEC,
    BM_SYSTEM_95PERC_SLO_VIOLATIONS_PERC,
    BM_SERVER_95PERC_SLO_VIOLATIONS_PERC,
    BM_SYSTEM_99PERC_SLO_VIOLATIONS_PERC,
    BM_SERVER_99PERC_SLO_VIOLATIONS_PERC,

    /*----------------------------------*/
    /* Inter run data fields */
    RUN_DATETIME,
    STREAM_SEED,
    CONFIGURATION_ID,
    CONFIGURATION_DESCRIPTION,
    REPETITION_ID,
    FINAL_TS,
    TOTAL_ALLOCATED_CAPACITY,
    ALLOCATED_CAPACITY_PER_SEC,
    SYSTEM_UTILIZATION,
    MEAN_SYSTEM_RESPONSE_TIME,
    TOTAL_JOBS_COMPLETED,
    TOTAL_SPIKE_JOBS_COMPLETED,
    TOTAL_SLO_95_VIOLATIONS,
    TOTAL_SLO_99_VIOLATIONS,
    SLO_95PERC_VIOLATIONS_PERCENTAGE,
    SLO_99PERC_VIOLATIONS_PERCENTAGE
}
