package it.uniroma2.utils;

public enum DataField {
    /* Intra run data fields */
    TIMESTAMP,
    R_0,
    MOVING_R_O,
    TO_BE_ACTIVE,
    ACTIVE,
    TO_BE_REMOVED,
    REMOVED,
    EVENT_TYPE,
    COMPLETING_SERVER_INDEX,
    PER_JOB_RESPONSE_TIME,
    JOBS_IN_SERVER,
    JOBS_IN_SYSTEM,
    STATUS_OF_SERVER,
    SPIKE_CURRENT_CAPACITY,

    /* Intra run transient data fields */
    AGG_SYSTEM_RESPONSE_TIME,
    AGG_SYSTEM_JOB_NUMBER,
    AGG_SYSTEM_UTILIZATION,
    AGG_SYSTEM_ALLOCATED_CAPACITY_PER_SEC,
    AGG_SERVER_RESPONSE_TIME,
    AGG_SERVER_JOB_NUMBER,
    AGG_SERVER_UTILIZATION,
    AGG_SERVER_ALLOCATED_CAPACITY_PER_SEC,

    /*----------------------------------*/
    /* Inter run data fields */
    RUN_DATETIME,
    STREAM_SEED,
    CONFIGURATION_ID,
    REPETITION_ID,
    FINAL_TS,
    TOTAL_ALLOCATED_CAPACITY,
    ALLOCATED_CAPACITY_PER_SEC,
    SYSTEM_UTILIZATION,
    MEAN_SYSTEM_RESPONSE_TIME,
    TOTAL_JOBS_COMPLETED,
    TOTAL_SPIKE_JOBS_COMPLETED,
    TOTAL_SLO_VIOLATIONS,
    SLO_VIOLATIONS_PERCENTAGE
}
